Type = "jscript"
Intro = ""
Desc = ""
OnOpen = "onOpen"
OnClose = "onClose"
OnConnect = "onConnected"
OnDisconnect = "onDisconnected"
OnBroadcast = "onBroadcast"
OnFocus = ""
OnLoseFocus = ""
OnKeyUp = "OnKeyUp"
OnHUDClick = ""
OnResponse = "onResponse"
OnAssist = "onAssist"
OnBuffer = ""
OnSubneg = ""
OnBufferMin = 0
OnBufferMax = 0
Channel = ""
Timers = []

[[Triggers]]
  ID = "d1fu8bc9ec0l0d71gvntjv"
  Name = "core.line"
  Enabled = true
  Match = "*"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.LineEvent('line')"
  SendTo = 0
  Sequence = 99
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = false
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = ""
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1fu8917k92j0j71gvnrr7"
  Name = "core.hpstart"
  Enabled = true
  Match = "^┌─+个人状态─+┬─+┐$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.LineEvent('core.hp')"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "event"
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1fu8f56oegs6v71gvo1b1"
  Name = "core.special"
  Enabled = true
  Match = "你现在会以下这些特技："
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.LineEvent('core.special')"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = false
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "event"
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1fu8ge06us6v171gvo1q2"
  Name = "core.title"
  Enabled = true
  Match = "^【[^【】]+】\\S+ (\\S+)\\(([a-zA-Z]+)\\)$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.LineEvent('core.title')"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "event"
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1fu8gpf5q3jrh71gvo26u"
  Name = "core.score"
  Enabled = true
  Match = "┌───人物详情────────────────────────┬───────┐"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.LineEvent('core.score')"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = false
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "event"
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1fu8i3m3s5bf071gvo2oo"
  Name = "core.skills"
  Enabled = true
  Match = "你目前所学到的所有技能"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.LineEvent(\"core.skills\")"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = false
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "event"
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1fu8ijbnp6kbc71gvo37d"
  Name = "core.noskill"
  Enabled = true
  Match = "你目前并没有学会任何技能。"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.LineEvent(\"core.noskill\")"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = false
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "event"
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1fu8jqba2q1kp71gvo585"
  Name = "App.Core.Room.OnName"
  Enabled = true
  Match = "^[^a-zA-Z0-9() ，。,.『』【】“”？?]{2,10}$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.FilterLineEvent(\"core.normalroomname\",\"core.roomname\")"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "room"
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1fu94a9h589n971gvo60u"
  Name = "core.exit"
  Enabled = true
  Match = "^    这里(唯一的出口是|明显的出口是|没有任何明显的出路)(.*)"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.LineEvent(\"core.onexit\")"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "event"
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1fud4ghmr5a2773s6n16r"
  Name = "core.item"
  Enabled = true
  Match = "^你身上带著下列这些东西\\(负重\\s*(\\S+)%\\)：$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.LineEvent(\"core.item\")"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "event"
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1fui7dgutrfff65of6lg"
  Name = "core.noitem"
  Enabled = true
  Match = "目前你身上没有任何东西。"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.LineEvent(\"core.noitem\")"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = false
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = ""
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1fv5gcsss6q2c726vp884"
  Name = "core.wrongway"
  Enabled = true
  Match = "这个方向没有出路。"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.LineEvent(\"core.wrongway\")"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = false
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "event"
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1fv5jkjvdotit726vp8pf"
  Name = "core.walkbusy"
  Enabled = true
  Match = "^(你现在正忙着呢。|你的动作还没有完成，不能移动|你逃跑失败|你被拦住了去路|什么都等你忙完了再说吧|等你忙完了再说吧|等你打完了架再说吧|你正忙，等有空了再说。|你觉得.*的感觉相当飘忽|你发现有洞穴内并不安全，还是还先清理掉虾兵虾将在走也不迟|你上一个动作还没有完成，先等等吧。)"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.LineEvent(\"core.walkbusy\")"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "event"
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1fv6n79t7ee4e726vqd4d"
  Name = "core.onecho"
  Enabled = true
  Match = "^这里没有 -echo- (.*)\\.(.*)。$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.FilterLineEvent(\"core.onecho\",\"core.echo\")"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "event"
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1fvajt6j0hivg72o6rfci"
  Name = "core.hpm"
  Enabled = true
  Match = "你目前的属性上限如下："
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.LineEvent('core.hpm')"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = false
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "event"
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Aliases]]
  ID = "d1fufevcofgvaa73s6n5s7"
  Name = "App.Core.Connect.OnAliasLogin"
  Enabled = true
  Match = "#login"
  Send = ""
  Script = "App.Core.Connect.OnAliasLogin"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Group = ""
  IgnoreCase = false
  KeepEvaluating = false
  Menu = false
  OmitFromLog = false
  Variable = ""
  ReverseSpeedwalk = false
  OmitFromOutput = false
  OmitFromCommandHistory = false

[[Aliases]]
  ID = "d1fv62osn8i7nf726vpqu6"
  Name = "queue"
  Enabled = true
  Match = "#(to|wait|do|loop|nobusy|sync|search|prepare)((\\s|\\|\\|).*)?$"
  Send = ""
  Script = "App.UserQueue.OnAlias"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Group = ""
  IgnoreCase = false
  KeepEvaluating = false
  Menu = false
  OmitFromLog = false
  Variable = ""
  ReverseSpeedwalk = false
  OmitFromOutput = false
  OmitFromCommandHistory = false

[[Aliases]]
  ID = "d1fv6bbo0pupo8726vq611"
  Name = "App.Alias.Stop"
  Enabled = true
  Match = "#stop"
  Send = ""
  Script = "App.Alias.Stop"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = false
  Group = ""
  IgnoreCase = false
  KeepEvaluating = false
  Menu = false
  OmitFromLog = false
  Variable = ""
  ReverseSpeedwalk = false
  OmitFromOutput = false
  OmitFromCommandHistory = false

[[RequiredParams]]
  Name = "id"
  Desc = "用户的id"
  Intro = "登陆用"

[[RequiredParams]]
  Name = "passw"
  Desc = "密码"
  Intro = "用户密码，登陆用"

[[RequiredParams]]
  Name = "num_cmds"
  Desc = "每心跳指令数"
  Intro = "应该是2的倍数，留空默认"
