(function () {
    return {
        DefaultNumCmds: 42,
        Drink: "shui dai",
        DrinkMin: 3,
        DrinkCommand: "drink shui dai",
        Food: "gan liang",
        FoodCommand: "eat gan liang",
        FoodMin: 5,
        GoldKeep: 2,
        GoldMax: 20,
        SilverMax: 2000,
        SilverKeep: 0,
        CoinMax: 2000,
        CoinKeep: 0,
        CashMax: 200,
        CashKeep: 30,
        LocBank: "23",
        HealBelow: 75,
        InspireBleow: 75,
        NeiliMin: 50,
        JingliMin: 50,
        LocDazuo: "1927",
        LocSleep: "179",
        LocRepair: "66",
        LocMaster: "",
        IDMaster: "",
        IDPass: "",
        NumDazuo: 0,
        NumTuna: 0,
        WeaponDurationMin: 40,
        ReloginDelay: 120000,
    }
})()