(function(){return {
    DefaultNumCmds:38,
    Drink:"shui dai",
    DrinkMin:3,
    DrinkCommand:"drink shui dai",
    Food:"gan liang",
    FoodCommand:"eat gan liang",
    FoodMin:5,
    GoldKeep:2,
    GoldMax:20,
    SilverMax:2000,
    SilverKeep:0,
    CoinMax:2000,
    CoinKeep:0,
    CashMax:200,
    CashKeep:30,
    LocBank:"23",
}})()