(function (App) {
    App.Include("src/quests/beiqi/beiqi.js")
    App.Include("src/quests/liandan/liandan.js")
    App.Include("src/quests/mq/mq.js")
    App.Include("src/quests/mq/letter.js")
    App.Include("src/quests/job/tiejiang.js")
    App.Include("src/quests/job/peiyao.js")
    App.Include("src/quests/job/fish.js")
    App.Include("src/quests/san/san.js")
    App.Include("src/quests/makeyao/makeyao.js")
    App.Include("src/quests/lianskill/lianskill.js")
    App.Include("src/quests/dazuo/dazuo.js")
    App.Include("src/quests/tuna/tuna.js")
    App.Include("src/quests/eatlu/eatlu.js")
    App.Include("src/quests/misc/quit.js")
    App.Include("src/quests/misc/stop.js")
    App.Include("src/quests/misc/fangqi.js")
    App.Include("src/quests/xuemo/xuemo.js")

})(App)