(function(app){
 let committeeModule=app.RequireModule("helllibjs/committee/committee.js")
  app.Committee=new committeeModule.Committee()
  app.Engine.BindEventHandler(function(event){app.Committee.OnEvent(event)})
  app.Engine.BindTimeHandler(function(){app.Committee.OnTime()})
  app.Positions["Connect"]=app.Committee.RegisterPosition("Connect")
  app.Committee.EventBus.BindEvent("connected",function(){app.Positions["Connect"].StartNewTerm()})
  app.Positions["Quest"]=app.Committee.RegisterPosition("Quest")
  app.Committee.EventBus.BindEvent("core.newquest",function(){app.Positions["Quest"].StartNewTerm()})
  app.Positions["Room"]=app.Committee.RegisterPosition("Room")
  app.Committee.EventBus.BindEvent("core.roomname",function(){app.Positions["Room"].StartNewTerm()})
  app.Positions["Combat"]=app.Committee.RegisterPosition("Combat")
  app.Committee.EventBus.BindEvent("core.newcombat",function(){app.Positions["Combat"].StartNewTerm()})
  app.Positions["Move"]=app.Committee.RegisterPosition("Move")
  app.Committee.EventBus.BindEvent("core.newmove",function(){app.Positions["Move"].StartNewTerm()})
  app.Positions["Command"]=app.Committee.RegisterPosition("Command")
  app.Committee.EventBus.BindEvent("core.newcommand",function(){app.Positions["Command"].StartNewTerm()})
  app.Plan=committeeModule.Plan
})(App)